<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('panorama_photos', function (Blueprint $table) {
            $table->id();
            $table->string('image_path');
            $table->integer('layer');
            $table->integer('height');
            $table->integer('width');
            $table->integer('x');
            $table->integer('y');
            $table->timestamps();
        });

        DB::table('panorama_photos')->insert([
            [
                'image_path' => '1.jpg',
                'layer' => 1,
                'height' => 500,
                'width' => 1080,
                'x' => 0,
                'y' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '2.jpg',
                'layer' => 2,
                'height' => 500,
                'width' => 1172,
                'x' => 1080,
                'y' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '3.jpg',
                'layer' => 3,
                'height' => 497.5,
                'width' => 1180,
                'x' => 2212,
                'y' => -1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '4.jpg',
                'layer' => 4,
                'height' => 500,
                'width' => 1192,
                'x' => 3349,
                'y' => -5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '5.jpg',
                'layer' => 5,
                'height' => 506,
                'width' => 1186,
                'x' => 4485,
                'y' => -8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '6.jpg',
                'layer' => 6,
                'height' => 511,
                'width' => 1213,
                'x' => 5611,
                'y' => -12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '7.jpg',
                'layer' => 8,
                'height' => 523,
                'width' => 1191,
                'x' => 6753,
                'y' => -13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '8.jpg',
                'layer' => 7,
                'height' => 502,
                'width' => 1158,
                'x' => 7900,
                'y' => -6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '9.jpg',
                'layer' => 9,
                'height' => 514,
                'width' => 1184,
                'x' => 9021,
                'y' => -12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '10.jpg',
                'layer' => 10,
                'height' => 511,
                'width' => 1186,
                'x' => 10161,
                'y' => -11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '11.jpg',
                'layer' => 11,
                'height' => 515,
                'width' => 1198,
                'x' => 11286,
                'y' => -13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '12.jpg',
                'layer' => 12,
                'height' => 518,
                'width' => 1174,
                'x' => 12423,
                'y' => -11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '13.jpg',
                'layer' => 13,
                'height' => 516,
                'width' => 1170,
                'x' => 13560,
                'y' => -11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '14.jpg',
                'layer' => 14,
                'height' => 509,
                'width' => 1187,
                'x' => 14685,
                'y' => -6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '15.jpg',
                'layer' => 15,
                'height' => 506,
                'width' => 1186,
                'x' => 15812,
                'y' => -4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '16.jpg',
                'layer' => 16,
                'height' => 505,
                'width' => 1169,
                'x' => 16944,
                'y' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '17.jpg',
                'layer' => 17,
                'height' => 508,
                'width' => 1170,
                'x' => 18077,
                'y' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '18.jpg',
                'layer' => 18,
                'height' => 515,
                'width' => 1169,
                'x' => 19207,
                'y' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '19.jpg',
                'layer' => 19,
                'height' => 526,
                'width' => 1170,
                'x' => 20335,
                'y' => -3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '20.jpg',
                'layer' => 20,
                'height' => 534,
                'width' => 1160,
                'x' => 21467,
                'y' => -6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '21.jpg',
                'layer' => 21,
                'height' => 526,
                'width' => 1161,
                'x' => 22597,
                'y' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '22.jpg',
                'layer' => 22,
                'height' => 542,
                'width' => 1167,
                'x' => 23715,
                'y' => -5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '23.jpg',
                'layer' => 23,
                'height' => 528,
                'width' => 1167,
                'x' => 24842,
                'y' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '24.jpg',
                'layer' => 24,
                'height' => 506,
                'width' => 1158,
                'x' => 25976,
                'y' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '25.jpg',
                'layer' => 25,
                'height' => 524,
                'width' => 1157,
                'x' => 27104,
                'y' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '26.jpg',
                'layer' => 26,
                'height' => 511,
                'width' => 1163,
                'x' => 28226,
                'y' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '27.jpg',
                'layer' => 27,
                'height' => 527,
                'width' => 1166,
                'x' => 29347,
                'y' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '28.jpg',
                'layer' => 28,
                'height' => 540,
                'width' => 1166,
                'x' => 30465,
                'y' => -4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '29.jpg',
                'layer' => 29,
                'height' => 534,
                'width' => 1165,
                'x' => 31587,
                'y' => -1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '30.jpg',
                'layer' => 30,
                'height' => 531,
                'width' => 1172,
                'x' => 32700,
                'y' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '31.jpg',
                'layer' => 31,
                'height' => 540,
                'width' => 1162,
                'x' => 33825,
                'y' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '32.jpg',
                'layer' => 32,
                'height' => 535,
                'width' => 1170,
                'x' => 34939,
                'y' => -4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image_path' => '33.jpg',
                'layer' => 33,
                'height' => 539,
                'width' => 1147,
                'x' => 36065,
                'y' => -2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('panorama_photos');
    }
};
